### ISSUE TITLE
Simplify package loading

### ISSUE THREAD

**Issue by cfraser2020** [Public-Health-Scotland/list-localities-profiles#15]
I think we need to add all packages to the global script to load there. Lots of instances of loading tidyverse for each script

### Tasks
- [x] Remove any commented out package loads
- [x] Remove any package loads which aren't used / needed
- [ ] Move all package loads to the Global script
