### ISSUE TITLE
Review messages and warnings

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/list-localities-profiles#58]
Removing tidylog would be a helpful first step - although useful for testing we should be able to disable it when 'doing a run' (helped by #15).

There are a handful of warnings I noticed referring to deprecated code - this usually means there's a better way to do things and worst case the code might stop working entirely with a future package update.

### Tasks
- [x] Remove usage of tidylog on production runs
- [x] https://github.com/Public-Health-Scotland/list-localities-profiles/issues/67
- [x] Replace deprecated functions
