### ISSUE TITLE
Summary table - Actual table in the final output

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/list-localities-profiles#64]
The summary table needs to be completely re-made so that the output is an actual table, rather than an image.

### Tasks
- [x] Pick a package that can build tables e.g. gt (https://gt.rstudio.com/), kable/kableExtra (https://rpubs.com/tf_peterson/kableDemo), flextable (https://davidgohel.github.io/flextable/index.html).
- [x] Build a small table with the correct rows etc.
- [x] Build the full table
- [x] Look at formatting to match / be inspired by the original

**Comment by Moohan** [comment]
Completed in #116
